fs

diff --git a/.github/workflows/Build_DS920+_7.2.0-64570_For_UNAS_T401P.yml b/.github/workflows/Build_DS920+_7.2.0-64570_For_UNAS_T401P.yml
--- a/.github/workflows/Build_DS920+_7.2.0-64570_For_UNAS_T401P.yml
+++ b/.github/workflows/Build_DS920+_7.2.0-64570_For_UNAS_T401P.yml
@@ -60,37 +60,21 @@ jobs:
           
       - name: 编译DTB
         run: |
-          cd /home/runner/redpill-load
-          chkurl=https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920.dts
-          HTTP_CODE=`curl -o /dev/null -s --head -w "%{http_code}" "${chkurl}"`
-          if [ ${HTTP_CODE} -ne 200 ]
-          then
-                      echo "不存在dts文件采用自动dtb补丁支持<=4盘"
-                      lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
-                      ./ext-manager.sh add ${lkmext}/redpill-dtb/rpext-index.json
-                       platform=${{matrix.platform}}
-                       version=${{matrix.version}}
-                       synoplatform=$(echo ${platform,,} | sed 's/+/p/g')
-                       synoversion=$(echo ${version} | awk -F - '{print $2}')
-                       key=${synoplatform}"_"${synoversion}
-                       echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-                       echo ${key}
-                      ./ext-manager.sh _update_platform_exts ${key} pocopico.dtb
-          else
-                       echo "加载原DTB驱动"
-                      ./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-dtb-static/rpext-index.json
-                      echo "更新原DTB驱动"
-                      ./ext-manager.sh _update_platform_exts ds920_64570 redpill-dtb-static
-                      echo "下载DTS文件"
-                       wget https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920.dts
-                      chmod +x ./redpill-qjs-dtb/src/dtc
-                      echo "编译DTS为DTB"
-                      ./redpill-qjs-dtb/src/dtc -I dts -O dtb -o ./ds920.dtb ./${{matrix.machine}}_ds920.dts
-                      echo "cp ./ds920.dtb /home/runner/redpill-load/custom/extensions/redpill-dtb-static/ds920_42218/model_ds920.dtb"
-                      dtbextfile="$(find custom -name model_ds920.dtb)"
-                      echo "复制编译好的DTB文件 ./ds920.dtb 到 ${dtbextfile} ..."
-                      sudo cp ./ds920.dtb ${dtbextfile}
-          fi
+                      cd /home/runner/redpill-load
+                      chkurl= https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
+                       wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill-dtb-static/releases/dtc
+                       chmod +x ./dtc
+                       echo "编译DTS为DTB"
+                        wget -O ${{matrix.machine}}_ds920p.dts ${chkurl}
+                       ./dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
+                       EXT_PATH="`./ext/dtbstatic/make.sh ./ds920p.dtb`"
+                       if [ -n "${EXT_PATH}" ]; then 
+                             echo "EXT_PATH: ${EXT_PATH}"
+                             ./ext-manager.sh add "${EXT_PATH}"
+                           else
+                             echo "loacl dtbstatic error"
+                             exit 1
+                       fi
           
       - name: 编译引导
         run: |
@@ -98,7 +82,7 @@ jobs:
           # 容错
           chmod +x type.sh && ./type.sh
           sed -i 's/\/images\/redpill\-/\/images\/${{matrix.machine}}\-/g' ./build-loader.sh
-          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds920_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
+          sudo BRP_JUN_MOD=0 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
       - name: 上传固件GitHub
         uses: actions/upload-artifact@master
         if: always()
