fix 202

diff --git a/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_NS202.yml b/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_NS202.yml
--- a/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_NS202.yml
+++ b/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_NS202.yml
@@ -84,13 +84,31 @@ jobs:
             chmod +x ./dtc
             echo "编译DTS为DTB"
             ./dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
-            echo "复制编译好的DTB文件"
-            sudo cp ./ds920p.dtb ext/dtbstatic/releases/user_model.dtb
+    
+            EXT_PATH="`./ext/dtbstatic/make.sh ./ds920p.dtb`"
+            if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl dtbstatic error"
+                  exit 1
+            fi
+            
+            echo "loacl localrss ..."
+                model=${{matrix.platform}}
+                version=${{matrix.version}}
 
-            dtbhash="`sha256sum ext/dtbstatic/releases/user_model.dtb | awk -F' ' '{print$1}'`"
-            sed -i "s|@@@PATH@@@|${PWD}|g" ext/dtbstatic/rpext-index.json ext/dtbstatic/recipes/universal.json
-            sed -i "s|@@@HASH@@@|${dtbhash}|g" ext/dtbstatic/recipes/universal.json
-            ./ext-manager.sh add "file://localhost${PWD}/ext/dtbstatic/rpext-index.json"
+                paturl=$(cat config/${model}/${version}/config.json | jq -r '.os .pat_url')
+                patmd5=$(cat config/${model}/${version}/config.json | jq -r '.os .hash')
+                EXT_PATH="`./ext/localrss/make.sh "${paturl}" "${patmd5}"`"
+                if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl localrss error"
+                  exit 1
+                fi 
+         
           fi
           
       - name: 编译引导
