Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -19,12 +19,20 @@ jobs:
       matrix:
         include:
           - platform: DS920+
-            version: 7.0.1-42218
+            version: 7.2.X
             machine: Custom
             user: chenxudong2020
     steps:
       - name: 检出文件
         uses: actions/checkout@v3
+        with:
+          submodules: true
+      - name: 获取版本
+        id: version
+        run: |
+          sh ./version.sh
+          echo "maxVersion=$(cat version.txt)" >> $GITHUB_OUTPUT    
+
       - name: 创建提示用户评论
         if: github.event_name == 'issues'
         id: comment
@@ -264,51 +272,32 @@ jobs:
       - name: 准备编译环境
         if: env.issues == 'true' && env.iscustom == 'true'
         run: |
-          # sudo apt update
           sudo apt-get install -y curl bspatch jq git
-          git clone -b develop https://github.com/jumkey/redpill-load.git /home/runner/redpill-load
-          cp -f type.sh /home/runner/redpill-load
-          cp -f user_config.json /home/runner/redpill-load/ds920p_user_config.json
-          # wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpillprod/releases/redpill-4.4.180plus-geminilake.tgz
-          # tar zxvf redpill-4.4.180plus-geminilake.tgz -C ./
-          # mv ./redpill.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
-
-      - name: 恢复lkms缓存
-        id: lkms
-        uses: actions/cache@v3
-        with:
-            path: /home/runner/redpill-lkm/output/
-            key: ${{ runner.os }}-lkms
-      - name: 创建lkms缓存
-        if: steps.lkms.outputs.cache-hit != 'true'
-        shell: pwsh
-        run: |
-            # 编译arpl使用的lkm 编译之后的ko统一命名redpill.ko 获取缓存之后统一使用此文件名 不再处理
-            git clone --recursive https://github.com/fbelavenuto/redpill-lkm.git /home/runner/redpill-lkm
-            cd /home/runner/redpill-lkm
-            ./compile-lkms.sh
-            cd /home/runner/redpill-lkm/output/
-            gunzip rp-geminilake-4.4.180-prod.ko.gz
-            mv rp-geminilake-4.4.180-prod.ko redpill.ko
-      - name: 安装lkms
-        run: |
-            cp /home/runner/redpill-lkm/output/redpill.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
-      - name: 保存lkms缓存
-        id: save_cache
-        if: steps.lkms.outputs.cache-hit != 'true'
-        uses: actions/cache/save@v3
-        with:
-          path: /home/runner/redpill-lkm/output/
-          key: ${{ runner.os }}-lkms
+          cp -rf redpill-load /home/runner/
+          pushd /home/runner/redpill-load
+          pip install -r requirements.txt
+          python syno.py ${{matrix.platform}} ${{steps.version.outputs.maxVersion}} 1
+          # cat config/${{matrix.platform}}/${{steps.version.outputs.maxVersion}}/config.json
+          popd
+          \cp type.sh /home/runner/redpill-load
+          \cp user_config.json /home/runner/redpill-load/ds920p_user_config.json
+          # 切换新内核支持7.2
+          wget https://raw.githubusercontent.com/wjz304/rp-ext/main/lkms/rp-geminilake-4.4.302-prod.ko.gz
+          gunzip ./rp-geminilake-4.4.302-prod.ko.gz
+          mv ./rp-geminilake-4.4.302-prod.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.302+.ko
 
       - name: 添加扩展驱动
         if: env.issues == 'true' && env.iscustom == 'true'
         run: |
-          cd /home/runner/redpill-load
-          ./ext-manager.sh add 'https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json'
-          ./ext-manager.sh add 'https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json'
-          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-acpid/rpext-index.json'
-          if [ -n "${{ env.driver }}" ]; then
+            cd /home/runner/redpill-load
+            rpext=https://raw.githubusercontent.com/wjz304/rp-ext/master
+            ./ext-manager.sh add "${rpext}/addons/boot-wait/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/addons/acpid2/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/addons/early-telnet/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/addons/hdddb/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/addons/nvmevolume/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/addons/wol/rpext-index.json"
+            if [ -n "${{ env.driver }}" ]; then
               driver=$(echo ${{ env.driver }} | awk '{gsub(/ /,"")}1')
               drivers=(${driver//,/ })
               for item in ${drivers[@]}
@@ -318,7 +307,7 @@ jobs:
                     ./ext-manager.sh add "${item}"
                   fi
               done
-          fi
+            fi
 
       - name: 编译DTB
         if: env.issues == 'true' && env.iscustom == 'true'
@@ -327,47 +316,53 @@ jobs:
            chkurl=${{ env.dts }}
            if [ ${{ env.dts }} ]
            then
-                            echo "加载原DTB驱动"
-                           ./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-dtb-static/rpext-index.json
-                           echo "更新原DTB驱动"
-                           ./ext-manager.sh _update_platform_exts ds920p_42218 redpill-dtb-static
-                           echo "下载DTS文件"
-                            wget -O ${{matrix.machine}}_ds920p.dts ${chkurl}
-                           chmod +x ./redpill-qjs-dtb/src/dtc
-                           echo "编译DTS为DTB"
-                           ./redpill-qjs-dtb/src/dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
-                           echo "cp ./ds920p.dtb /home/runner/redpill-load/custom/extensions/redpill-dtb-static/ds920p_42218/model_ds920p.dtb"
-                           dtbextfile="$(find custom -name model_ds920p.dtb)"
-                           echo "复制编译好的DTB文件 ./ds920p.dtb 到 ${dtbextfile} ..."
-                           sudo cp ./ds920p.dtb ${dtbextfile}
+                wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill-dtb-static/releases/dtc
+                chmod +x ./dtc
+                echo "编译DTS为DTB"
+                 wget -O ${{matrix.machine}}_ds920p.dts ${chkurl}
+                ./dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
+                EXT_PATH="`./ext/dtbstatic/make.sh ./ds920p.dtb`"
+                if [ -n "${EXT_PATH}" ]; then 
+                      echo "EXT_PATH: ${EXT_PATH}"
+                      ./ext-manager.sh add "${EXT_PATH}"
+                    else
+                      echo "loacl dtbstatic error"
+                      exit 1
+                fi
+                
+                echo "loacl localrss ..."
+                    model=${{matrix.platform}}
+                    version=${{steps.version.outputs.maxVersion}}
+    
+                    paturl=$(cat config/${model}/${version}/config.json | jq -r '.os .pat_url')
+                    patmd5=$(cat config/${model}/${version}/config.json | jq -r '.os .hash')
+                    EXT_PATH="`./ext/localrss/make.sh "${paturl}" "${patmd5}"`"
+                    if [ -n "${EXT_PATH}" ]; then 
+                      echo "EXT_PATH: ${EXT_PATH}"
+                      ./ext-manager.sh add "${EXT_PATH}"
+                    else
+                      echo "loacl localrss error"
+                      exit 1
+                    fi 
+
            else
-                 echo "不存在dts文件采用自动dtb补丁支持<=4盘"
-                 lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
-                 ./ext-manager.sh add ${lkmext}/redpill-dtb/rpext-index.json
-                  platform=${{matrix.platform}}
-                  version=${{matrix.version}}
-                  synoplatform=$(echo ${platform,,} | sed 's/+/p/g')
-                  synoversion=$(echo ${version} | awk -F - '{print $2}')
-                  key=${synoplatform}"_"${synoversion}
-                  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-                  echo ${key}
-                 ./ext-manager.sh _update_platform_exts ${key} pocopico.dtb
+                echo "不存在dts文件采用自动dtb补丁支持<=4盘"
+                lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
+                ./ext-manager.sh add ${lkmext}/addons/dtbpatch/rpext-index.json
            fi
 
       - name: 编译引导
         if: env.issues == 'true' && env.iscustom == 'true'
         run: |
           cd /home/runner/redpill-load
-          # 容错
-          chmod +x type.sh && ./type.sh
           sed -i 's/\/images\/redpill\-/\/images\/${{matrix.machine}}\-/g' ./build-loader.sh
-          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
+          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json BRP_PLATFORM_KVER=geminilake-4.4.302 ./build-loader.sh '${{matrix.platform}}' '${{steps.version.outputs.maxVersion}}'
           cp -f /home/runner/redpill-load/ds920p_user_config.json /home/runner/redpill-load/images
       - name: 上传固件GitHub
         uses: actions/upload-artifact@master
         if: env.issues == 'true' && env.iscustom == 'true'
         with:
-          name: ${{matrix.machine}}-${{matrix.platform}}-${{matrix.version}}-b${{steps.date.outputs.now}}
+          name: ${{matrix.machine}}-${{matrix.platform}}-${{steps.version.outputs.maxVersion}}-b${{steps.date.outputs.now}}
           path: /home/runner/redpill-load/images
       - name: 编译结束更新评论
         if: env.issues == 'true' && env.iscustom == 'true'
@@ -379,7 +374,7 @@ jobs:
           update-mode: replace
           body: |
             ${{ env.issueauth }} 您好.
-            您自定义的 DS920+ 已开始构建完成. 请前往下面的 URL 查看详细信息.
+            您自定义的 DS920+ 版本：${{steps.version.outputs.maxVersion}} 已开始构建完成. 请前往下面的 URL 查看详细信息.
             > ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
             ----
           emoji: hooray
@@ -401,6 +396,6 @@ jobs:
           update-mode: replace
           body: |
             ${{ env.issueauth }} 您好.
-            您自定义的 DS920+ 构建失败. 请前往下面的 URL 查看详细信息对body进行修改并请重新触发编译(Close & Reopen).
+            您自定义的 DS920+ 版本: ${{steps.version.outputs.maxVersion}} 构建失败. 请前往下面的 URL 查看详细信息对body进行修改并请重新触发编译(Close & Reopen).
             > ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           emoji: confused
