Update Build_DS1520+_6.2.4-25556_For_UNAS_T201P.yml

diff --git a/.github/workflows/Build_DS1520+_6.2.4-25556_For_UNAS_T201P.yml b/.github/workflows/Build_DS1520+_6.2.4-25556_For_UNAS_T201P.yml
--- a/.github/workflows/Build_DS1520+_6.2.4-25556_For_UNAS_T201P.yml
+++ b/.github/workflows/Build_DS1520+_6.2.4-25556_For_UNAS_T201P.yml
@@ -1,4 +1,4 @@
-name: Build DS1520+ 6.2.4-25556 For UNAS_T201P
+name: Build DS1520+ 6.2.4-25556 For UNAS_NS202
 
 on:
   schedule:
@@ -19,13 +19,15 @@ jobs:
       matrix:
         include:
           - platform: DS1520+
-            version: 7.0.1-42218
-            machine: UNAS_T201P
+            version: 6.2.4-25556
+            machine: UNAS_NS202
             user: chenxudong2020
 
     steps:
       - name: 检出项目文件
         uses: actions/checkout@v3
+        with:
+          submodules: true
         
       - name: 获取当前时间
         id: date
@@ -43,27 +45,33 @@ jobs:
         run: |
           # sudo apt update
           sudo apt-get install -y curl bspatch jq git
-          git clone -b develop https://github.com/jumkey/redpill-load.git /home/runner/redpill-load
+          # git clone -b develop https://github.com/pocopico/redpill-load.git /home/runner/redpill-load
+          cp -rf redpill-load /home/runner/
+          pushd /home/runner/redpill-load
+          # make config
+          pip install -r requirements.txt
+          python syno.py ${{matrix.platform}} ${{matrix.version}} 1
+          cat config/${{matrix.platform}}/${{matrix.version}}/config.json
+          popd
+          
           cp -f type.sh /home/runner/redpill-load
           wget https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/config/${{matrix.machine}}_ds920p_user_config.json -O /home/runner/redpill-load/ds920p_user_config.json
-          # 编译arpl使用的lkm
-          git clone --recursive https://github.com/fbelavenuto/redpill-lkm.git
-          cd ./redpill-lkm
-          ./compile-lkms.sh
-          cd ..
-          zip -9 lkm.zip -j ./redpill-lkm/output/*
-          mkdir lkmdir
-          unzip lkm.zip -d ./lkmdir
-          gunzip ./lkmdir/rp-geminilake-4.4.180-prod.ko.gz
-          mv ./lkmdir/rp-geminilake-4.4.180-prod.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
+          # 使用wjz304的lkm
+          wget https://raw.githubusercontent.com/wjz304/rp-ext/main/lkms/rp-geminilake-4.4.59-prod.ko.gz
+          gunzip ./rp-geminilake-4.4.59-prod.ko.gz
+          mv ./rp-geminilake-4.4.59-prod.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.59+.ko
           
       - name: 添加扩展驱动
         run: |
-          cd /home/runner/redpill-load
-          ./ext-manager.sh add 'https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json'
-          ./ext-manager.sh add 'https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json'
-          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-acpid/rpext-index.json'
-          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json'
+            cd /home/runner/redpill-load
+            rpext=https://raw.githubusercontent.com/wjz304/rp-ext/master
+            ./ext-manager.sh add "${rpext}/addons/boot-wait/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/addons/acpid2/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/modules/r8169/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/modules/igb/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/modules/r8168/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/modules/e1000e/rpext-index.json"
+             
           
       - name: 编译DTB
         run: |
@@ -72,44 +80,51 @@ jobs:
           HTTP_CODE=`curl -o /dev/null -s --head -w "%{http_code}" "${chkurl}"`
           if [ ${HTTP_CODE} -ne 200 ]
           then
-                      echo "不存在dts文件采用自动dtb补丁支持<=4盘"
-                      lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
-                      ./ext-manager.sh add ${lkmext}/redpill-dtb/rpext-index.json
-                       platform=${{matrix.platform}}
-                       version=${{matrix.version}}
-                       synoplatform=$(echo ${platform,,} | sed 's/+/p/g')
-                       synoversion=$(echo ${version} | awk -F - '{print $2}')
-                       key=${synoplatform}"_"${synoversion}
-                       echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-                       echo ${key}
-                      ./ext-manager.sh _update_platform_exts ${key} pocopico.dtb
+            echo "不存在dts文件采用自动dtb补丁支持<=4盘"
+            lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
+            ./ext-manager.sh add ${lkmext}/addons/dtbpatch/rpext-index.json
           else
-                       echo "加载原DTB驱动"
-                      ./ext-manager.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill-dtb-static/rpext-index.json
-                      echo "更新原DTB驱动"
-                      ./ext-manager.sh _update_platform_exts ds920p_42218 redpill-dtb-static
-                      echo "下载DTS文件"
-                       wget https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
-                      chmod +x ./redpill-qjs-dtb/src/dtc
-                      echo "编译DTS为DTB"
-                      ./redpill-qjs-dtb/src/dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
-                      echo "cp ./ds920p.dtb /home/runner/redpill-load/custom/extensions/redpill-dtb-static/ds920p_42218/model_ds920p.dtb"
-                      dtbextfile="$(find custom -name model_ds920p.dtb)"
-                      echo "复制编译好的DTB文件 ./ds920p.dtb 到 ${dtbextfile} ..."
-                      sudo cp ./ds920p.dtb ${dtbextfile}
+            echo "下载DTS文件"
+            wget https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
+            wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill-dtb-static/releases/dtc
+            chmod +x ./dtc
+            echo "编译DTS为DTB"
+            ./dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
+    
+            EXT_PATH="`./ext/dtbstatic/make.sh ./ds920p.dtb`"
+            if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl dtbstatic error"
+                  exit 1
+            fi
+            
+            echo "loacl localrss ..."
+                model=${{matrix.platform}}
+                version=${{matrix.version}}
+
+                paturl=$(cat config/${model}/${version}/config.json | jq -r '.os .pat_url')
+                patmd5=$(cat config/${model}/${version}/config.json | jq -r '.os .hash')
+                EXT_PATH="`./ext/localrss/make.sh "${paturl}" "${patmd5}"`"
+                if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl localrss error"
+                  exit 1
+                fi 
+         
           fi
           
       - name: 编译引导
         run: |
           cd /home/runner/redpill-load
-          # 容错
-          chmod +x type.sh && ./type.sh
           sed -i 's/\/images\/redpill\-/\/images\/${{matrix.machine}}\-/g' ./build-loader.sh
-          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
+          sudo BRP_JUN_MOD=0 BRP_DEBUG=1 BRP_USER_CFG=ds920p_user_config.json BRP_PLATFORM_KVER=geminilake-4.4.59 ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
       - name: 上传固件GitHub
         uses: actions/upload-artifact@master
         if: always()
         with:
             name: ${{matrix.machine}}-${{matrix.platform}}-${{matrix.version}}-b${{steps.date.outputs.now}}
             path: /home/runner/redpill-load/images
-
