Update Build_DS920+_6.2.4-25556_For_UNAS_T201P.yml

diff --git a/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_T201P.yml b/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_T201P.yml
--- a/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_T201P.yml
+++ b/.github/workflows/Build_DS920+_6.2.4-25556_For_UNAS_T201P.yml
@@ -1,4 +1,4 @@
-name: Build DS920+ 6.2.4-25556 For UNAS_T201P
+name: Build DS720+ 6.2.4-25556 For UNAS_NS202
 
 on:
   schedule:
@@ -18,9 +18,9 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - platform: DS920+
+          - platform: DS720+
             version: 6.2.4-25556
-            machine: UNAS_T201P
+            machine: UNAS_NS202
             user: chenxudong2020
 
     steps:
@@ -67,51 +67,53 @@ jobs:
             rpext=https://raw.githubusercontent.com/wjz304/rp-ext/master
             ./ext-manager.sh add "${rpext}/addons/boot-wait/rpext-index.json"
             ./ext-manager.sh add "${rpext}/addons/acpid2/rpext-index.json"
-            ./ext-manager.sh add "${rpext}/modules/r8125/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/modules/r8169/rpext-index.json"
+            ./ext-manager.sh add "${rpext}/modules/igb/rpext-index.json"
+             
           
       - name: 编译DTB
         run: |
-              cd /home/runner/redpill-load
-              chkurl=https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
-              HTTP_CODE=`curl -o /dev/null -s --head -w "%{http_code}" "${chkurl}"`
-              if [ ${HTTP_CODE} -ne 200 ]
-              then
-                echo "不存在dts文件采用自动dtb补丁支持<=4盘"
-                lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
-                ./ext-manager.sh add ${lkmext}/addons/dtbpatch/rpext-index.json
-              else
-                echo "下载DTS文件"
-                wget https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
-                wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill-dtb-static/releases/dtc
-                chmod +x ./dtc
-                echo "编译DTS为DTB"
-                ./dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
-        
-                EXT_PATH="`./ext/dtbstatic/make.sh ./ds920p.dtb`"
-                if [ -n "${EXT_PATH}" ]; then 
-                      echo "EXT_PATH: ${EXT_PATH}"
-                      ./ext-manager.sh add "${EXT_PATH}"
-                    else
-                      echo "loacl dtbstatic error"
-                      exit 1
-                fi
-                
-                echo "loacl localrss ..."
-                    model=${{matrix.platform}}
-                    version=${{matrix.version}}
+          cd /home/runner/redpill-load
+          chkurl=https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
+          HTTP_CODE=`curl -o /dev/null -s --head -w "%{http_code}" "${chkurl}"`
+          if [ ${HTTP_CODE} -ne 200 ]
+          then
+            echo "不存在dts文件采用自动dtb补丁支持<=4盘"
+            lkmext=https://raw.githubusercontent.com/wjz304/rp-ext/master
+            ./ext-manager.sh add ${lkmext}/addons/dtbpatch/rpext-index.json
+          else
+            echo "下载DTS文件"
+            wget https://raw.githubusercontent.com/${{matrix.user}}/Redpill_Build/master/dts/${{matrix.machine}}_ds920p.dts
+            wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill-dtb-static/releases/dtc
+            chmod +x ./dtc
+            echo "编译DTS为DTB"
+            ./dtc -I dts -O dtb -o ./ds920p.dtb ./${{matrix.machine}}_ds920p.dts
     
-                    paturl=$(cat config/${model}/${version}/config.json | jq -r '.os .pat_url')
-                    patmd5=$(cat config/${model}/${version}/config.json | jq -r '.os .hash')
-                    EXT_PATH="`./ext/localrss/make.sh "${paturl}" "${patmd5}"`"
-                    if [ -n "${EXT_PATH}" ]; then 
-                      echo "EXT_PATH: ${EXT_PATH}"
-                      ./ext-manager.sh add "${EXT_PATH}"
-                    else
-                      echo "loacl localrss error"
-                      exit 1
-                    fi 
-             
-              fi
+            EXT_PATH="`./ext/dtbstatic/make.sh ./ds920p.dtb`"
+            if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl dtbstatic error"
+                  exit 1
+            fi
+            
+            echo "loacl localrss ..."
+                model=${{matrix.platform}}
+                version=${{matrix.version}}
+
+                paturl=$(cat config/${model}/${version}/config.json | jq -r '.os .pat_url')
+                patmd5=$(cat config/${model}/${version}/config.json | jq -r '.os .hash')
+                EXT_PATH="`./ext/localrss/make.sh "${paturl}" "${patmd5}"`"
+                if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl localrss error"
+                  exit 1
+                fi 
+         
+          fi
           
       - name: 编译引导
         run: |
@@ -124,4 +126,5 @@ jobs:
         with:
             name: ${{matrix.machine}}-${{matrix.platform}}-${{matrix.version}}-b${{steps.date.outputs.now}}
             path: /home/runner/redpill-load/images
+
 
